[package]
name = "viz"
version = "0.1.0"
edition = "2018"

[dependencies]
cam-geom = "0.9.0"
forceatlas2 = { path = "../.." }
gio = "0.9.1"
glib = "0.10.3"
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
gtk = "0.9.2"
nalgebra = "0.27"
rand = "0.8.3"
static-rc = "0.4.0"
