[package]
name = "viz"
version = "0.1.0"
edition = "2018"

[dependencies]
forceatlas2 = { path = "../.." }
gio = "0.9.0"
glib = "0.10.3"
gdk = "0.13.0"
gdk-pixbuf = "0.9.0"
gtk = "0.9.2"
rand = "0.8.3"
