[package]
name = "viz"
version = "0.1.0"
edition = "2021"

[dependencies]
cam-geom = "0.11.0"
forceatlas2 = { path = "../.." }
gio = "0.14.8"
glib = "0.14.8"
gdk = "0.14.3"
gdk-pixbuf = "0.14.0"
gtk = "0.14.3"
nalgebra = "0.29.0"
parking_lot = "0.11.2"
rand = "0.8.4"
static-rc = "0.5.0"
