[package]
name = "viz"
version = "0.1.0"
edition = "2021"

[dependencies]
cam-geom = "^0.11"
forceatlas2 = { path = "../.." }
gio = "^0.14"
glib = "^0.14"
gdk = "^0.14"
gdk-pixbuf = "^0.14"
gtk = "^0.14"
nalgebra = "^0.29"
parking_lot = "^0.11"
rand = "^0.8"
static-rc = "^0.5"
