[package]
name = "viz"
version = "0.1.0"
edition = "2021"

[dependencies]
cam-geom = "0.12.0"
forceatlas2 = { path = "../..", features = ["barnes_hut"] }
gio = "0.15.10"
glib = "0.15.10"
gdk = "0.15.4"
gdk-pixbuf = "0.15.10"
gtk = "0.15.4"
nalgebra = "0.30.1"
parking_lot = "0.12.0"
rand = "0.8.5"
static-rc = "0.5.0"
